--------------------------------------------------------
--  File created - petak-veljaèe-03-2017   
--------------------------------------------------------
DROP TABLE "CROZ"."ADDRESS" cascade constraints;
DROP TABLE "CROZ"."CITY" cascade constraints;
DROP TABLE "CROZ"."CONTACT" cascade constraints;
DROP TABLE "CROZ"."COUNTRY" cascade constraints;
DROP TABLE "CROZ"."CROZUSER" cascade constraints;
DROP TABLE "CROZ"."SEX" cascade constraints;
DROP SEQUENCE "CROZ"."S_TABLES_ID";
--------------------------------------------------------
--  DDL for Sequence S_TABLES_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CROZ"."S_TABLES_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 147 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "CROZ"."ADDRESS" 
   (	"ID" NUMBER, 
	"STREET" VARCHAR2(50 BYTE), 
	"STREET_NO" VARCHAR2(5 BYTE), 
	"CITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "CROZ"."CITY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"ZIP_CODE" VARCHAR2(10 BYTE), 
	"COUNTRY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "CROZ"."CONTACT" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SEX_ID" NUMBER, 
	"ADRESS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

  CREATE TABLE "CROZ"."COUNTRY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"ALPHA_2" VARCHAR2(2 BYTE), 
	"ALPHA_3" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CROZUSER
--------------------------------------------------------

  CREATE TABLE "CROZ"."CROZUSER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(256 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"INSTM" DATE, 
	"UPDTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEX
--------------------------------------------------------

  CREATE TABLE "CROZ"."SEX" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CROZ.ADDRESS
SET DEFINE OFF;
Insert into CROZ.ADDRESS (ID,STREET,STREET_NO,CITY_ID) values ('33','Andrije Hebranga','32','22');
Insert into CROZ.ADDRESS (ID,STREET,STREET_NO,CITY_ID) values ('134','Pariska','33','22');
REM INSERTING into CROZ.CITY
SET DEFINE OFF;
Insert into CROZ.CITY (ID,NAME,ZIP_CODE,COUNTRY_ID) values ('22','Zagreb','10000','1');
Insert into CROZ.CITY (ID,NAME,ZIP_CODE,COUNTRY_ID) values ('44','London','WC	','5');
REM INSERTING into CROZ.CONTACT
SET DEFINE OFF;
Insert into CROZ.CONTACT (ID,FIRST_NAME,LAST_NAME,PHONE,EMAIL,SEX_ID,ADRESS_ID) values ('1','Marko','Valentic','098-992-8421','m_valentic@yahoo.com','1','33');
Insert into CROZ.CONTACT (ID,FIRST_NAME,LAST_NAME,PHONE,EMAIL,SEX_ID,ADRESS_ID) values ('135','Davor','Lovric','092-323-323','croz@croz.com','1','134');
REM INSERTING into CROZ.COUNTRY
SET DEFINE OFF;
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('1','Croatia','HR','HRV');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('2','France','FR','FRA');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('3','Germany','DE','DEU');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('4','Ireland','IE','IRL');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('5','Great B','GB','GBR');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('6','Hungary','HU','HUN');
Insert into CROZ.COUNTRY (ID,NAME,ALPHA_2,ALPHA_3) values ('136','Portugal','PR','PRT');
REM INSERTING into CROZ.CROZUSER
SET DEFINE OFF;
Insert into CROZ.CROZUSER (ID,NAME,LASTNAME,USERNAME,PASSWORD,INSTM,UPDTM) values ('1','baba','baba','baba','Z+1Y95VAfBeSnRLvCReybYwDPf59JfTEHFMixUeWKNY=$8nb8N/jrXO1ai+sx',to_date('12.01.17','DD.MM.RR'),null);
REM INSERTING into CROZ.SEX
SET DEFINE OFF;
Insert into CROZ.SEX (ID,NAME) values ('1','MALE');
Insert into CROZ.SEX (ID,NAME) values ('2','FEMALE');
--------------------------------------------------------
--  DDL for Index COUNTRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."COUNTRY_PK" ON "CROZ"."COUNTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."ADRESS_PK" ON "CROZ"."ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."TABLE1_PK" ON "CROZ"."SEX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTACT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."CONTACT_PK" ON "CROZ"."CONTACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_ALPHA_2
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."COUNTRY_ALPHA_2" ON "CROZ"."COUNTRY" ("ALPHA_2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."CITY_PK" ON "CROZ"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEX_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."SEX_NAME" ON "CROZ"."SEX" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."COUNTRY_NAME" ON "CROZ"."COUNTRY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CROZUSERE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."CROZUSERE_PK" ON "CROZ"."CROZUSER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_ALPHA_3
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."COUNTRY_ALPHA_3" ON "CROZ"."COUNTRY" ("ALPHA_3") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CROZ"."CITY_NAME" ON "CROZ"."CITY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CROZUSER
--------------------------------------------------------

  ALTER TABLE "CROZ"."CROZUSER" ADD CONSTRAINT "CROZUSERE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CROZ"."CROZUSER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CROZUSER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CROZUSER" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CROZUSER" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CROZUSER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CROZ"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CROZ"."CITY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CITY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

  ALTER TABLE "CROZ"."COUNTRY" ADD CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CROZ"."COUNTRY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."COUNTRY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "CROZ"."ADDRESS" ADD CONSTRAINT "ADRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CROZ"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEX
--------------------------------------------------------

  ALTER TABLE "CROZ"."SEX" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."SEX" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."SEX" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "CROZ"."CONTACT" ADD CONSTRAINT "CONTACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CROZ"."CONTACT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CONTACT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CONTACT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CONTACT" MODIFY ("PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "CROZ"."CONTACT" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "CROZ"."ADDRESS" ADD CONSTRAINT "CITY_ID" FOREIGN KEY ("CITY_ID")
	  REFERENCES "CROZ"."CITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "CROZ"."CITY" ADD CONSTRAINT "COUNTRY_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "CROZ"."COUNTRY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "CROZ"."CONTACT" ADD CONSTRAINT "ADRESS_FK" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "CROZ"."ADDRESS" ("ID") ENABLE;
 
  ALTER TABLE "CROZ"."CONTACT" ADD CONSTRAINT "SEX_FK" FOREIGN KEY ("SEX_ID")
	  REFERENCES "CROZ"."SEX" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ADDRESS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CROZ"."T_ADDRESS_ID" 
    BEFORE INSERT OR UPDATE ON ADDRESS
    FOR EACH ROW
BEGIN
       if inserting then
             if :NEW.ID is null then
                    select S_TABLES_ID.nextval into :NEW.id from dual;
             end if;
       
       end if;
END;
/
ALTER TRIGGER "CROZ"."T_ADDRESS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CITY_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CROZ"."T_CITY_ID" 
    BEFORE INSERT OR UPDATE ON CITY
    FOR EACH ROW
BEGIN
       if inserting then
             if :NEW.ID is null then
                    select S_TABLES_ID.nextval into :NEW.id from dual;
             end if;
       
       end if;
END;
/
ALTER TRIGGER "CROZ"."T_CITY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CONTACT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CROZ"."T_CONTACT_ID" 
    BEFORE INSERT OR UPDATE ON CONTACT
    FOR EACH ROW
BEGIN
       if inserting then
             if :NEW.ID is null then
                    select S_TABLES_ID.nextval into :NEW.id from dual;
             end if;
       
       end if;
END;
/
ALTER TRIGGER "CROZ"."T_CONTACT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_COUNTRY_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CROZ"."T_COUNTRY_ID" 
    BEFORE INSERT ON COUNTRY
    FOR EACH ROW
BEGIN
       if inserting then
             if :NEW.ID is null then
                    select S_TABLES_ID.nextval into :NEW.id from dual;
             end if;
       
       end if;
END;
/
ALTER TRIGGER "CROZ"."T_COUNTRY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_CROZUSER_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CROZ"."T_CROZUSER_ID" 
    BEFORE INSERT OR UPDATE ON CROZUSER
    FOR EACH ROW
BEGIN
       if inserting then
             if :NEW.ID is null then
                    select S_TABLES_ID.nextval into :NEW.id from dual;
             end if;
             :NEW.INSTM := sysdate;
       elsif updating then
             :NEW.UPDTM := sysdate;    
       end if;
END;
/
ALTER TRIGGER "CROZ"."T_CROZUSER_ID" ENABLE;
